services:
  frontend:
    image: dvnpn/efrei-frontend-crisiview:latest
    container_name: crisiview-front-staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production