# --- Identification du projet ---
sonar.projectKey=efrei-frontend-crisiview
sonar.projectName=EFREI - Crisiview Frontend
sonar.projectVersion=1.0

# --- Chemins des sources ---
sonar.sources=app
sonar.sourceEncoding=UTF-8

# --- Exclusions ---
sonar.exclusions=**/.next/**, **/node_modules/**, **/.vercel/**, public/**, next.config.ts, postcss.config.mjs, eslint.config.mjs

# --- Configuration future du Coverage ---
# Si un jour des tests Jest ou Vitest sont ajoutés
# sonar.tests=app
# sonar.test.inclusions=**/*.test.tsx, **/*.test.ts
# sonar.javascript.lcov.reportPaths=coverage/lcov.info